### PR TITLE
Frame -> Pallet changes - Fix old SRML links and module references, removed upgrade-key references, etc.

### PR DESCRIPTION
**Pull request by laboon**
There were many ../srml/.. links that I changed to ../frame/..

I also changed reference to Substrate-included runtime modules to pallets. 

Upgrade-key was removed in a PR, and replaced with generic sudo key, so I just removed that sentence. https://github.com/paritytech/substrate/pull/2018

Added Frame and Pallet to the glossary

### CODE REVIEW

**Comment by laboon** [comment]
fixes #162

**Review by lsaether — APPROVED** [review]

**Comment by Swader** [comment]
@fgimenez looks like our CI is stuck in a loop - let's hold off on merging this until that's resolved.

**Comment by fgimenez** [comment]
@Swader should be fixed now

**Comment by Swader** [comment]
Thanks @fgimenez!

**Pull request merged**
