### PR TITLE
Migrate to Docusaurus v2

### PR DESCRIPTION
**Pull request by nam-hle**
The PR is to migrate two websites to the Docusaurus v2. Here is noticeable changes:

# Images

- Moved all documentation-related images from the sites' `static` folder to `/docs/assets`. It reduces the number of duplicated images between two sites and be less confused when referencing them in docs (all image paths will be started with `assets/...`, no more mixed with `img/...`)

**Note**: There are 02 referenced images I can't find elsewhere in `docs/maintain-guides-how-to-vote-councillor`.

# Documentation

- Some broken links: I changed to `#` for simplicity. Please fix them with proper links for me (by review maybe :D)
- `` element: it needs to change `src` attribute from absolute one to `require`, otherwise the Docusaurus will throw not found errors.

# Injection dictionary values

We can't replace `{{ ... }}` syntax in HTML files with true values after the building step due to the new Docusaurus server-side mechanism. So my solution is:
- Fetch the necessary values then saved them in a JSON file temporarily.
- After the markdown abstract syntax trees (AST) are created, a new `remarkable` [plugin](https://github.com/nam-hle/polkadot-wiki/blob/migrate/scripts/injectPlugin.js) will transform placeholder value to real one from candidate tree nodes (`text`, `paragraph`,...) in build time **before** generating HTML files.

# i18n

- Docusaurus v2 requires a specific directory structure for i18n (see [more](https://docusaurus.io/docs/i18n/introduction) ):
```
website/i18n
└── zh-CN
    ├── code.json: contains keys for general UI labels as well as our custom page keys
    │
    ├── docusaurus-plugin-content-docs
    │   ├── current: contains translated docs
    │   │   ├── doc1.md
    │   │   └── doc2.md
    │   └── current.json: keys for category labels in sidebar
    │
    └── docusaurus-theme-classic: keys for specific components
        ├── footer.json
        └── navbar.json
```

- With new [`Translate API`](https://docusaurus.io/docs/docusaurus-core#translate), we can translate [homepage](https://github.com/nam-hle/polkadot-wiki/blob/migrate/website-v2/src/pages/index.js), footer as well as category label in the sidebar completely. 
- We also only need to save the source string in `i18n/en`, other languages can be downloaded in build time. Currently, I only added the scripts to download two current supported language documentations: Russian and Chinese Simplified. (Crowdin CLI does not allow to download multiple languages once so I use two separate scripts for it. Please let me know if there are possible solutions)
- The `docs/assets` dir also needs to be copied into each language: `website/i18n/<lang>/docusaurus-plugin-content-docs/current/assets`.

# Scripts

- Clean cache
- Run parallel:
	- Mirror docs
	- Mirror assets into language directories
	- Fetch and save will-inject dictionary values
	- Generate registry table (Polkadot only)
	- Download translated docs (then copy in case of Kusama)
- Build (injection will be done here)
- Post-process

### CODE REVIEW

**Comment by salmad3** [comment]
Btw @Swader I ran this locally last week and from my knowledge it ran successfully - mirrored pages were okay and injections were there.

Just seems to be some merge conflicts now.

**Comment by Swader** [comment]
Very good. @laboon I propose a merge to get this into master asap and continue building CI and content on 2.0. Should be crowdin compatible now too

**Comment by nam-hle** [comment]
Thanks for testing. I will resolve the conflicts ASAP

**Comment by rmnprkrl** [comment]
FYI @nam-hle: We're (W3F) going to be using Simple Analytics (SA) for both Polkadot and Kusama wiki. SA are completely cookieless and don't gather any sensitive information so don't need to be included in the cookie consent manager.

I've already added the script into current v1 (@Swader is aware): https://github.com/w3f/polkadot-wiki/pull/2163
Docusaurus 2 should offer the same config so you can just re-use it and add it into this migration PR right away before the merge.

Let me know in case of any problem @nam-hle, thanks!

More info: https://simpleanalytics.com

**Comment by nam-hle** [comment]
@rmnprkrl I just added the SA two new websites. Please tell me if anything could be improved ;)

**Comment by rmnprkrl** [comment]
Looks good @nam-hle thx!

**Comment by emresurmeli** [comment]
Thanks @nam-hle going to be testing things out on your branch as a final check to see if all is working as intended:

- [x] run locally
- [x] mirroring works
- [x] build works
- [x] injection works

edit: All checks look good

**Pull request merged**
