### PR TITLE
Update Prod with Latest Changes

### LINKED ISSUE #2257: Add information about light vs full on Ledger page
Also please include link to Zondax repo which includes list of supported extrinsics

hirschenberger
I have a democracy lock that I can't get rid of. I use a ledger and follow the instructions here: https://wiki.polkadot.network/docs/learn-ledger/#removing-expired-democracy-locks
When I issue the removeVote extrinsic polkadot.js (or the browser-plugin) tells me "not supported".
Hmm, "not supported" is coming from the Ledger. I don't know if they removed support for this extrinsic at some point. Looking into it.
iso joined the room.
Bill | W3F
hirschenberger: removeVote should be supported, but this is the "full" version. Are you using the "light" version of the app for the Nano S? https://github.com/Zondax/ledger-polkadot#democracy
hirschenberger
Ah yes I use the light version bc. I also want to support kusama
Bill | W3F
Looking through that list, it looks like none of the Democracy extrinsics are available in the light version

### PR DESCRIPTION
**Pull request by salmad3**
* resolves #2257

* add content to kusama ledger pg

* Update docs/kusama-ledger.md

Co-authored-by: Bill Laboon <laboon@users.noreply.github.com>

* Update docs/kusama-ledger.md

Co-authored-by: Bill Laboon <laboon@users.noreply.github.com>

* Update docs/kusama-ledger.md

Co-authored-by: Bill Laboon <laboon@users.noreply.github.com>

Co-authored-by: Bill Laboon <laboon@users.noreply.github.com>

### CODE REVIEW

**Comment by salmad3** [comment]
I left something to be updated on one of the files just to test out the staging. 
Generally speaking, after checking the staging pages, would we push any further updates to master directly?

**Comment by DrW3RK** [comment]
From my understanding, 

https://staging.polkadot.network/  and https://staging.kusama.network/ are served by the **Master** branch

https://wiki.polkadot.network/  and https://guide.kusama.network/ are served by the **Prod** branch

We initiate pull requests on **Master** branch and merge the branches back to it

Once everything looks good on **Master** branch, we use `git rebase `(instead of merge) to push changes to **Prod** branch

**Comment by jakehemmerle** [comment]
> From my understanding,
> 
> https://staging.polkadot.network/ and https://staging.kusama.network/ are served by the **Master** branch
> 
> https://wiki.polkadot.network/ and https://guide.kusama.network/ are served by the **Prod** branch

yes 


> Once everything looks good on **Master** branch, we use `git rebase `(instead of merge) to push changes to **Prod** branch

both merge or rebase will cause the same behavior if `prod` <= `master` (ie no commits are ever added directly to `prod`)

you should NOT see a "Merged master into prod" or a similar commit; it should just fast-forward. If you see the former and you're not sure how to fix, let me know.

**Comment by jakehemmerle** [comment]
@DannyS03 I think I initially said we should just push stuff to master and then put up PRs against prod for master, but I think that will be more difficult to review multiple PRs in one PR and there will be other issues causing code divergence because we will have to use merge commits instead of fast forwards if we use PR style here.

Feel free to just merge these into prod and we will do all code review as PRs against master (just like we've been doing). I recommend doing the merging of master to prod locally: checkout and pull master, checkout and pull prod, and then `git merge master` on prod, and then push prod.

**Pull request merged**
