### PR TITLE
[Draft] Prototype Indexer + GraphQL for Fetching On-Chain Data

### LINKED ISSUE #4693: Fix Auction Tool on the Wiki
image

> https://parachains.info/auctions/kusama - this says the next auction (Auction 78) starts today, but the Kusama Guide says the next auction is Auction 74 and starts 12 May. https://guide.kusama.network/docs/learn-auction/

- [ ] Replace the tool with a link to Parachains Info for the time being
- [ ] Fix the issue with the Auction Tool

### PR DESCRIPTION
**Pull request by CrackTheCode016**
General draft / tracking PR for replacing any heavy RPC operations with an Indexer (for now, trying [SubSquid](https://www.subsquid.io/)).  This would also allow for curated data to be more efficiently gathered from multiple chains, i.e., Polkadot or Kusama.

For now, the indexer impl resides here: https://github.com/CrackTheCode016/wiki-squid

Current Goals / TODO: 

- [x] Streamline GraphQL Calls within React components
- [x] Fix the existing Auction tool as the first implementation
- [x] Provide a set of common queries to use across components (for both future/current components)?
- [x] Configure indexer to supply useful data 'lazily', and only as required

### CODE REVIEW

**Comment by CrackTheCode016** [comment]
Data is now being pulled in from the indexer (locally). The indexer still needs some work to streamline some crucial data points, of which must be implemented:

- [x] Onboarding info
- [x] Lease info
- [x] Fix dates

Once this is done, it will be ready for the initial review.

**Comment by CrackTheCode016** [comment]
@DrW3RK @filippoweb3 

This is now able to be deployed and tested locally, as the indexer is running.  Any UI/UX changes are welcome.  For anyone reviewing, viewing how the auctions are fetched and how their respective parameters are calculated can be [found here](https://github.com/CrackTheCode016/wiki-squid/blob/main/src/processor.ts#L110).  There might be slight inaccuracies with the lease period, however, it was hard to tell as multiple services are off by a day or two (i.e., subscan, parachains.info). (points to anyone who can figure out why!)

This works for both Polkadot and Kusama and is self-updating, meaning as auctions are being started/closed, the API updates.  There is also error handling for when data is unavailable, with the direction to create an issue within this repo. Conditional rendering is also implemented.

For testing, Kusama is deployed right now.

For the reviewers.

- Are there any requested UI/UX changes? 
- Is there any additional info that should be part of this component or the indexer?
- For now, only Kusama is deployed so be sure to `yarn start:kusama` :) 

Screenshot 2023-05-29 at 7 06 41 PM
Screenshot 2023-05-29 at 7 06 35 PM

**Review by filippoweb3 — CHANGES_REQUESTED** [review]
lgtm, great tool! 

At this stage, we need to remove the GitHub action that updates the schedule that was used by the previous indexer and anything else related to it, as now all that stuff is redundant.

**Comment by CrackTheCode016** [comment]
> lgtm, great tool!
> 
> At this stage, we need to remove the GitHub action that updates the schedule that was used by the previous indexer and anything else related to it, as now all that stuff is redundant.

@filippoweb3 Addressed - should be good to go.  When we get the proper link, then we can remove the action on GH itself as well, and update the README.

**Review by filippoweb3 — APPROVED** [review]
This PR is good to go from my side. Just requesting Radha's final approval.

**Comment by DrW3RK** [comment]
Can be merged after the indexer is moved to the W3F repo

**Comment by CrackTheCode016** [comment]
Both indexers for Polkadot and Kusama have been hosted.

We can also remove the Action for it, since these replace that functionality.

**Review by filippoweb3 — APPROVED** [review]
lgtm! :)

**Pull request merged**
