### PR TITLE
Add Conditional Rendering/Injections Updates to Build Fix

### PR DESCRIPTION
**Pull request by salmad3**
Original: https://github.com/w3f/polkadot-wiki/pull/2669

### CODE REVIEW

**Comment by jakehemmerle** [comment]
What does this PR do? It just looks like a bunch of linting that your editor added

**Comment by salmad3** [comment]
It readded the injects but primarily it changes `_` -> `*` to avoid conflict in the rendering on the pages that use conditional rendering/injects

**Comment by jakehemmerle** [comment]
> It readded the injects but primarily it changes `_` -> `*` to avoid conflict in the rendering on the pages that use conditional rendering/injects

@DannyS03 Okay be sure to mention that otherwise reviewers don't know what they're for.

Also, since injection fixing and punctuation stuff are two orthogonal things, they should be split into seperate PRs, but since this just does the linting just mention that. You also changed all the single quotes to double quotes?

**Comment by salmad3** [comment]
> > It readded the injects but primarily it changes `_` -> `*` to avoid conflict in the rendering on the pages that use conditional rendering/injects
> 
> @DannyS03 Okay be sure to mention that otherwise reviewers don't know what they're for.
> 
> Also, since injection fixing and punctuation stuff are two orthogonal things, they should be split into seperate PRs, but since this just does the linting just mention that. You also changed all the single quotes to double quotes?

Right, forgot to link the original PR which describes the changes. I updated the description above. I also merged this into the branch you created so it picks up the changes and builds. 

The quotes should be double -> single (same with what your changes had in the docusaurus config)

**Pull request merged**
