### PR TITLE
Update build wallet.md

### PR DESCRIPTION
**Pull request by daynight97**
This is a batch paper wallet for Polkadot (and btc, eth and eos).  It can generate 1 to 1000 wallets and export as pdf. It using combination of drawing on canvas (mouse movement) and Polkadot-js api random hex function to generate raw seed. This method will increase the entropy and make the private keys generated more random and secured.

### CODE REVIEW

**Comment by lsaether** [comment]
@daynight97 Is it open source?

**Comment by daynight97** [comment]
Hi,  

Yes, it is open source, see
https://github.com/globaldefi/batch-paper-wallet
TQ 

daynight 

On 2020-09-10 11:54, Logan Saether wrote: 

@daynight97 Is it open source?

**Comment by daynight97** [comment]
@lsaether Have you take a look at the source? It is open source, using polkadot.js api. I created the bundle using browserify.

**Comment by lsaether** [comment]
I'm unable to read the source. Is there a reason not to upload the original files before they are minified? This would greatly help out the review from someone who would like to verify the source before using the tools.

**Comment by daynight97** [comment]
> I'm unable to read the source. Is there a reason not to upload the original files before they are minified? This would greatly help out the review from someone who would like to verify the source before using the tools.

@lsaether Please see paperwalletc4.php in the github (https://github.com/globaldefi/batch-paper-wallet) , non minified version. Thanks.

**Comment by daynight97** [comment]
@lsaether Any reason why our wallet still not included in your wiki? Already open source our wallet.

**Comment by Swader** [comment]
Sorry I don't think we'll be able to include this. It is too rudimentary to be considered a wallet, and too dangerous to just outright include.

**Pull request closed without merging**
