### PR TITLE
Fix ribbon

### PR DESCRIPTION
**Pull request by ansonla3**

### CODE REVIEW

**Review by Swader — CHANGES_REQUESTED** [review]
It's too flush with the edges, we need some padding, but the ribbon isn't as much of a problem as the menu is - if you open the menu on mobile and try scrolling, it's still broken. That should be fixed asap.

image

**Comment by Swader** [comment]
Also keep in mind that these fixes will need to be applied to Kusama guide too

**Comment by krichard410** [comment]
@ansonla3 a Wiki issue I created overlaps with this PR, did you want to add that into this PR? It's #674

**Comment by Swader** [comment]
Sorry I'm going to close this in favor of a fix I'm preparing for #678 and #664 and #643

**Pull request closed without merging**
