### PR TITLE
Added "Improve this wiki" ribbon

### LINKED ISSUE #318: Add a header for "Contribution Welcome"

### PR DESCRIPTION
**Pull request by Swader**
Closes #318

### CODE REVIEW

**Comment by lsaether** [comment]
image

I think this is the right idea but I'm not so sure about the ribbon design, versus a bar on top of the main nav bar. Will implement what I'm thinking and post a screenshot for comparison. 

EDIT:

My alternate submission:

image

**Comment by Swader** [comment]
I'm a fan of the familiar ribbon design, it's what I'm used to. A top-line in the header screams "urgent current temporary notification" to me, and doesn't sit well long-term, in my eyes at least. But let's hear others, I can live with either :) @laboon @ansonla3

**Comment by laboon** [comment]
I like the ribbon design, personally.  It's how I would expect a message like this to be delivered.

**Comment by ansonla3** [comment]
either one is fine. personally like @lsaether one

**Pull request merged**
