### PR TITLE
Update third-party supported wallets section

### LINKED ISSUE #3798: Update the Treasury Funded wallets section
- Update the "Supports" column with relevant details for wach wallet
- Add treasury funding details for Talisman wallet https://polkadot.polkassembly.io/treasury/148

### LINKED ISSUE #3799: Update Talisman funding information
Add information about treasury funding for Talisman.

[Proposal 148](https://polkadot.polkassembly.io/treasury/148)

### PR DESCRIPTION
**Pull request by filippoweb3**
- [x] Update info about Talisman
- [x] Update "Supports" column

### CODE REVIEW

**Comment by filippoweb3** [comment]
@DrW3RK I deleted the "Custody" and "Supports" columns as they are all non-custodial and all support staking

**Comment by filippoweb3** [comment]
Added column "Staking support" as requested by @DrW3RK

**Comment by DrW3RK** [comment]
Maybe add an "Additional Features" column where we can include misc features like Governance, Social recovery, Ledger Support, Parachain support, teleports etc.

**Comment by DrW3RK** [comment]
We also have to highlight these are non-custodial wallets prominently

**Comment by filippoweb3** [comment]
Added non-custodial column.

Regarding "Additional Features"
Should I test all these wallets first before writing down this detailed information? Is it not too detailed? Also the tables already look quite compressed.

**Comment by DrW3RK** [comment]
Testing the wallets would be great! I was thinking of mostly skimming through their websites for what features they support.

**Review by DrW3RK — APPROVED** [review]

**Comment by DrW3RK** [comment]
@filippoweb3 I added a few updates. If everything looks good, please merge the PR. Thanks!

**Pull request merged**
