### PR TITLE
Add DotAppStore to the Wiki

### PR DESCRIPTION
**Pull request by DrW3RK**
https://dotappstore.com/ - allows for upvoting by the community

Funded by the treasury https://polkadot.polkassembly.io/referenda/214#dfDuFNuuNeqnGLycCkSQ

### CODE REVIEW

**Comment by filippoweb3** [comment]
@DrW3RK what you think if we add this on the main App page? https://wiki.polkadot.network/docs/apps-index
We also could add the link to the Polkadot website section about apps https://polkadot.network/ecosystem/dapps/

**Review by filippoweb3 — APPROVED** [review]
lgtm, see previous comment

**Comment by DrW3RK** [comment]
Adding to https://wiki.polkadot.network/docs/apps-index is a good idea. We can list this as well https://polkadot.network/ecosystem/dapps/

**Comment by DrW3RK** [comment]
@filippoweb3 Let me know if this works.

image

Also, I figured https://app.talisman.xyz/explore and https://web.subwallet.app/home/dapps have done a great job listing the apps. Probably will add them in appropriate locations through another PR later.

**Review by filippoweb3 — APPROVED** [review]
lgtm

**Pull request merged**
