### PR TITLE
Added in more info for payouts

### LINKED ISSUE #478: Add new logics for payouts on Kusama and the reason behind it
on https://wiki.polkadot.network/docs/en/mirror-maintain-guides-how-to-nominate-kusama

One can read: "In order to claim them (i.e., add them to your account), **you must manually claim them**. See the Claiming Rewards section of the Staking wiki page for more details""

We should specify the latest changes given payouts mechanism is evolving fast, from _auto-payout_ to _payout activated by nominator_ and now _payout can be activated by validator or nominator_. An explanation of the logic behind it should be there: to optimise effectiveness of payouts and make as little state storage on Kusama.

### PR DESCRIPTION
**Pull request by krichard410**
I added in another detail to this page to clarify the manual claiming process when it comes to rewards. 
Aiming to Fix #478

### CODE REVIEW

**Comment by Swader** [comment]
I accidentally merged before the CI passed. Can you do a fix-pass for that please?

**Comment by krichard410** [comment]
@Swader I think it shows it passes on my end, the only thing that failed looks to be the Fleek add-on. 
Screen Shot 2020-07-12 at 10 23 05 PM

**Comment by Swader** [comment]
Ah, yup. Hmm @lsaether can you check what's up with the fleek thing?

**Comment by lsaether** [comment]
I tried out fleek when I was setting up IPFS hosting for the wiki, but ended up not going with it. Just deleted the project from Fleek's dashboard. Hopefully that fixes it but I can't tell because I don't see Fleek on the CI checks (and neither do I see GH actions).

The checks for #693 for instance only show CircleCI ones:

image

**Comment by lsaether** [comment]
NVM - I see now that the CI is running on commits to master.

**Pull request merged**
