### PR TITLE
NFT Page

### LINKED ISSUE #2455: NFTs Page
- NFT basics
- A comparison
  - Perhaps obstacles of some of the inherent problems of first generation vs. next generation (Polkadot :)) 
- NFTs in the Polkadot ecosystem, for instance:  
  - https://rmrk.app/
  - https://kodadot.xyz/
  - https://unique.network/
  - https://enjin.io/blog/efinity
  - PolkadotAssetJS
  - Moonbeam integrates NFTs
  - Substrate & NFTs
  - Statemine

- ~Can sit in the build section after "Oracles"~ Sits in learn section for now.

### PR DESCRIPTION
**Pull request by salmad3**
~Resolves #2455~

### CODE REVIEW

**Comment by Swader** [comment]
Would you like me to take a stab at this? Happy to do it

**Comment by salmad3** [comment]
> Would you like me to take a stab at this? Happy to do it

If you have the time I would say you would be the best for this 😄

**Comment by Swader** [comment]
You got it, will have something for you soon!

**Comment by salmad3** [comment]
Closing this as Bruno will submit a new PR for the page

**Pull request closed without merging**
