### PR TITLE
[WIP] Add references to ink!athon Boilerplate & Restructure ink! content

### LINKED ISSUE #5242: [Feature Request] Restructure ink!-related stuff
Page: https://wiki.polkadot.network/docs/build-open-source

In the course of https://github.com/w3f/polkadot-wiki/pull/5241, I've noticed that, currently, there is a dedicated "[ink! Smart Contracts](https://wiki.polkadot.network/docs/build-open-source#ink-smart-contracts)" section but a lot of ink!-related stuff is also under "[Tools, APIs, and Languages](https://wiki.polkadot.network/docs/build-open-source#tools-apis-and-languages)". This should all be reorganized under the ink! section IMO. (At least that was the reason I've overseen a lot of the stuff there in the first place, because I'm mainly interested in ink!-stuff.)

Also, during reorganization make sure to clearly classify frontend- and/or contract-related stuff. E.g. `typechain-polkadot` is classified under "Easy Smart Contract Development" which is a bit misleading IMO.

### PR DESCRIPTION
**Pull request by wottpal**
Closes #5242

- [x] Added/Reorganized references to ink!athon boilerplate (inkathon.xyz). See this [sub0 Workshop](https://www.youtube.com/watch?v=SoNLZfsd0mQ), if you're not aware of ink!athon.
- [x] Took the freedom to make your husky `pre-commit` script compatible with [nvm](https://github.com/nvm-sh/nvm) (which is very commonly used). 
- [x] Minor status/typo improvements
- [x] Restructure ink! Content
- [x] Add ink!athon to dApp build-guide, add links there, and remove capi

### CODE REVIEW

**Comment by CrackTheCode016** [comment]
This is super useful, thank you! 

When you feel it is good for review, ping me or mark it as Ready for Review and I'd be happy to do so.  

It could be we expand https://wiki.polkadot.network/docs/build-guide with some of this new contracts content as well.  Feel free to add to that if you want ;)

**Comment by wottpal** [comment]
@CrackTheCode016 Thanks for this suggestion, I just went for it and added it there as well. Also, I made the changes suggested in #5242. Please have a look & review :)

**Review by CrackTheCode016 — APPROVED** [review]
LGTM, thank you SO much for this!  Definitely an actionably way to improve developer resources 

@DrW3RK some of the tables in build-open were changed - before I merge this shouldn't break anything right?

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/developer-experience-must-be-our-1-priority/3957/44

**Pull request merged**
