### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by w3fbot**
Enjoy!

### CODE REVIEW

**Comment by Swader** [comment]
@fgimenez does this not get CI-checked for links? Do crowdin PRs not go through CI?

**Comment by fgimenez** [comment]
@Swader the circleCI config in the branch used to propose the PR doesn't have the latest changes with the link checker step, instead of https://github.com/w3f/polkadot-wiki/blob/df2d61140c8071ceaa8c8498c0bf56f08ced1f8b/.circleci/config.yml it should look like https://github.com/w3f/polkadot-wiki/blob/master/.circleci/config.yml

Not sure if that branch is updated automatically or you need to maintain it manually?

**Comment by Swader** [comment]
I do not know :/

**Comment by Swader** [comment]
@ansonla3?

**Comment by ansonla3** [comment]
@Swader  looking into

**Pull request merged**
