### PR TITLE
fix internal link

### PR DESCRIPTION
**Pull request by nuke-web3**

### CODE REVIEW

**Comment by laboon** [comment]
@NukeManDan - Does this link not work for you?  It works for me and goes to https://thousand-validators.kusama.network/#/

**Comment by laboon** [comment]
please re-open if this is still an issue

**Comment by nuke-web3** [comment]
This should redirect to our internal page on 1k validators. Its an internal reference for both programs

**Comment by nuke-web3** [comment]
@laboon I can't seem to reopen... But we should

**Comment by nuke-web3** [comment]
https://wiki.polkadot.network/docs/en/thousand-validators

**Pull request merged**
