### PR TITLE
WIP: Sub0 banner

### PR DESCRIPTION
**Pull request by je-boska**

### CODE REVIEW

**Comment by je-boska** [comment]
@DrW3RK I'm placing a Sub0 banner on this site and some others. Found this implementation which says it was created for Decoded, would you like me to use this one? If so, I'd like to adjust the styling a bit before we deploy it.

**Comment by rmnprkrl** [comment]
@je-boska will update the UI design a little before merging

**Comment by je-boska** [comment]
@DrW3RK Would it be possible to build a preview of this PR? Finalising the styling now.

**Comment by DrW3RK** [comment]
It is possible to run the Staging build and deploy on branches and see the preview here https://staging.polkadot.network/
but this seems to be a fork. We can merge to `master` branch and see the preview on https://staging.polkadot.network/

Should I do it now?

**Comment by DrW3RK** [comment]
Only when we merge the changes to the `prod` branch, it gets reflected on the Wiki pages.

**Comment by je-boska** [comment]
Ok good to know! I'm still doing some adjustments, will let you know when it's done and then we can preview it.

**Comment by je-boska** [comment]
@DrW3RK This should be ready to preview now!

**Review by DrW3RK — APPROVED** [review]

**Comment by DrW3RK** [comment]
Can be previewed here https://staging.polkadot.network/

image

This looks good. But, people usually do not land on the homepage directly as they are directed to Wiki pages through search engines
Is it possible to add this banner for all the Wiki pages?

**Comment by DrW3RK** [comment]
FYI, Substrate docs show a popup message on every doc https://docs.substrate.io/fundamentals/blockchain-basics/

**Comment by je-boska** [comment]
@DrW3RK Thank you, this can be merged to production.

Putting it on every page like on docs would require some more not pre-existing logic to be implemented; a close button and session storage management. If you can't get rid of it, the banner would get too annoying IMO -- in particular on mobile, where it blocks a big part of the screen. 

While I don't mind implementing these things in a couple of days or so, I need to move on to more high priority tasks right now, and we need the banner live. Thanks for your support! I might get back to placing it on all pages soon.

**Comment by DrW3RK** [comment]
Thanks! Previously we used Announcement bar which gives an option to close https://docusaurus.io/docs/api/themes/configuration#announcement-bar

**Pull request merged**
