### PR TITLE
Revert "Enhancements to Protocol Page"

### PR DESCRIPTION
**Pull request by joepetrowski**
Reverts w3f/polkadot-wiki#2957

Clarifies some address stuff.

### CODE REVIEW

**Comment by DrW3RK** [comment]
Conditional rendering is removed and address info is updated. LGTM.

**Comment by salmad3** [comment]
Why revert 2957?

**Comment by DrW3RK** [comment]
I was going to ask on Element, given the sense of urgency. If we were to revert #2967, this page on Kusama guide needs to be pulled down - https://guide.kusama.network/docs/build-protocol-info/

**Comment by DrW3RK** [comment]
Context for Reverting #2967 shared in TechEd channel

**Pull request merged**
