### PR TITLE
Add dark theme for Polkadot Wiki

### LINKED ISSUE #2758: [Feature Request] Dark mode & switch button?
My eyes would thank you **so so so much**

I know this is possible, and within branding guidelines without too much effort. Here is an example from @DrW3RK :
https://github.com/DrW3RK/polkadot-mooc
image

### PR DESCRIPTION
**Pull request by DrW3RK**

### CODE REVIEW

**Comment by DrW3RK** [comment]
The toggle is enabled. But the whole CSS file and the website seems to have been customized only for the light mode. Too many places to make changes. Feel free to commit the changes to the color scheme.

**Comment by salmad3** [comment]
How should we approach the Kusama Guide?

**Comment by DrW3RK** [comment]
The same way. With the custom CSS in place, there seem to be quite a few adjustments that need to be made to have dark mode seamlessly work on Polakdot Wiki. Once we figure that out, we can do the same on Kusama guide

**Comment by salmad3** [comment]
Based on our intent to revamp, closing this PR. Please reopen if otherwise.

**Pull request closed without merging**
