### PR TITLE
Added Gridlock Wallet details

### PR DESCRIPTION
**Pull request by DerekfromMadison**
Added Gridlock Wallet information to the wiki

### CODE REVIEW

**Comment by DrW3RK** [comment]
Hi @DerekfromMadison Thank you very much for adding the info on Gridlock wallet to the Wiki. Is your wallet opensource? Were you ever funded by the Polkadot Treasury or W3F grants?

**Comment by DerekfromMadison** [comment]
Hi @DrW3RK - We are funded by a VC firm very very close to Polkadot and are in the process of applying for a treasury grant. I figured we should get on the wiki prior to the formal grant process.

**Comment by DrW3RK** [comment]
Thanks for providing additional context! Let me discuss this internally and either open the wallets page to closed source projects or create a dedicated page/section for enterprise wallets like yours. Here is a PR with the relevant discussion for your reference https://github.com/w3f/polkadot-wiki/pull/4713

**Comment by filippoweb3** [comment]
Hello @DerekfromMadison,

Regarding your request to add information to the Wiki, we regret to inform you that due to the closed-source nature of the content you would like to include, we are unable to approve your request. The Wiki primarily supports open-source projects within the Polkadot ecosystem. The main concern is that people might not be able to verify the authenticity of closed-source projects, posing a security risk, especially since Wiki users may not necessarily have coding expertise. Without the ability to inspect the code, it becomes challenging to ensure the project's credibility. I close this PR, you are welcome to submit a new PR when the project becomes open source. Thank you for your understanding.

**Pull request closed without merging**
