### PR TITLE
Add Ethereum 2.0 Comparison

### PR DESCRIPTION
**Pull request by joepetrowski**

### CODE REVIEW

**Review by Swader — APPROVED** [review]

**Comment by Swader** [comment]
Wondering if it would be okay to also link to a more [in-depth comparison series](https://bitfalls.com/tag/pfe/) for those who want more.

**Comment by Swader** [comment]
@joepetrowski CI fixed, can you please rebase and re-push this branch, we'll need to re-merge to trigger a build. The CI will now ignore translations and will not block builds containing 404s, only flag them in PRs.

**Comment by fgimenez** [comment]
Given that it was merged into master the changes have already been deployed, i've checked with @joepetrowski Only the existing branches (still not merged) need to rebase in order to get the new settings for the link checker.

**Comment by Swader** [comment]
Oh snap, really cool, thanks for checking, good stuff!

**Pull request merged**
