### PR TITLE
Added Westend WND units

### PR DESCRIPTION
**Pull request by trevor-crypto**

### CODE REVIEW

**Comment by salmad3** [comment]
Thank you @trevor-crypto,

Since WND tokens are part of the testnet and hold no economic value,  do you think its better to just add content about WNDs and compare it to the native token units? Could even mention something along the lines of "Westend having the same parameters as Polkadot like session length and governance enactment period."

**Comment by trevor-crypto** [comment]
@DannyS03 Sorry, I'm a bit new to Substrate/Polkadot. Doesn't Kusama also have no economic value? I'm not really sure if it's appropriate to put this Westend info here, but I was looking for it and it wasn't in an accessible location (within source code network configs)

**Comment by salmad3** [comment]
Oh no worries at all. So Kusama does have real economic value. Perhaps this page can offer some meaningful insight: https://wiki.polkadot.network/docs/learn-kusama-vs-polkadot/#:~:text=Although%20they%20share%20many%20parts,conservative%2C%20prioritizing%20stability%20and%20dependability.

How about we add the WND units under the `Obtaining Testnet DOT` section?

**Comment by trevor-crypto** [comment]
> How about we add the WND units under the Obtaining Testnet DOT section?
@DannyS03 That's a good idea. I will push a change.

Thanks for the info

**Review by salmad3 — APPROVED** [review]

**Pull request merged**
