### PR TITLE
Add Dedicated Slashing Page

### PR DESCRIPTION
**Pull request by paradox-tt**
Unformatted document

### CODE REVIEW

**Review by salmad3 — CHANGES_REQUESTED** [review]
- would advise adding an instance or example where applicable
- maintain-slashing.md would be better as slashing is a key aspect of maintaining the network, so having information on slashing in general and then leading into best practices seems like a better approach where we can use content on slashing already available on the wiki and treat this doc as the main content for slashing

**Comment by paradox-tt** [comment]
I'll get some examples posted in Polkassembly.

I agree with the advised document flow.

**Comment by salmad3** [comment]
After the fact, we can add the page to both sidebars for the Polkadot Wiki and Kusama Guide

**Comment by emresurmeli** [comment]
Let's add the page to the sidebars and add 1-3 examples

cc: @paradox-tt

**Review by paradox-tt — COMMENTED** [review]
Sorry for the delay, please find examples tabulated below.

**Comment by DrW3RK** [comment]
Thank you @paradox-tt Will review this soon!

**Review by DrW3RK — APPROVED** [review]
Thank you @paradox-tt Merging this PR and will create a new PR for linking appropriate Wiki docs and polish the content further

**Pull request merged**
