### PR TITLE
fixes #1813, Use esm module imports synthax instead of commonJS and update @polkadotjs/api to version 4.0.3

### LINKED ISSUE #1813: Make Github Actions use NodeJS 14+ due to new ESM requirement
Polkadot API now uses ESM which breaks on anything below NodeJS 14.

### PR DESCRIPTION
**Pull request by Yuripetusko**
use esm synthax for node scripts

### CODE REVIEW

**Comment by Swader** [comment]
Thanks but I don't think this is needed any more with API version 4.0.3?

**Comment by Swader** [comment]
Ah, no, I didn't test our custom scripts on below v14 of node yet, could very well be it doesn't work. But rather than make the custom commands more complex, I would rather use this opportunity to clean house a little bit.

**Comment by Yuripetusko** [comment]
Ok fair enough @Swader. I have now updated this PR to use ESM modules purely without using babel transpiler. But for some reason CircleCI fails (I cannot access it to see the details)

**Comment by Swader** [comment]
Yeah we're using some kind of docker image with an outdated node it seems, need to figure out what's up or how to update it.

image

I would *really* love to move away from Circle and onto Github Actions in full (#1731), as Circle is just a nuisance at this point.

**Comment by Swader** [comment]
Due to the error message shown, I don't think these v13 nodes are the problem (though they should absolutely also be updated), instead, I think this is the offending line: https://github.com/w3f/polkadot-wiki/blob/master/.circleci/config.yml#L20 - which means we should somehow update node inside of that image. And I have no idea what that image is, where to find it, or how to update it.

**Comment by Yuripetusko** [comment]
Looks like it is this particular image

https://github.com/w3f/polkadot-wiki/blob/master/.circleci/config.yml#L20

**Comment by Swader** [comment]
Ah, looks like it's this: https://github.com/w3f/link-checker

**Comment by Swader** [comment]
I do not know or like Docker, are you able to figure out how to update this from node10 to node14?

**Comment by Yuripetusko** [comment]
I hate docker myself, but I can try :D might have to fork docker config

**Comment by Swader** [comment]
Actually, this image itself depends on Circle, so even if we fix it it'll be troublesome to move from Circle to Github actions. I would actually propose we remove the link checker altogether and build an alternative because this one never really worked well anyway. Yes, let's do that.

**Comment by Yuripetusko** [comment]
Should I remove linkchecked from circleci config in this PR?

**Comment by Swader** [comment]
Yes please, let's kill it with fire

**Comment by Yuripetusko** [comment]
Remove linkchecker CircleCI section

**Comment by Yuripetusko** [comment]
Whoop! it's all green now

**Comment by Swader** [comment]
Hah, nice, thanks!

**Pull request merged**
