### PR TITLE
[donotmerge] Polkadot Guide Section  (see #2392)

### PR DESCRIPTION
**Pull request by Juan-DiegoC**
Creating PR to address issue #1569. 

The work done so far will create the index page for the Guides Section in preparation for future simple guides specifically for this Guide Section.

Before this section gets merged we should have a couple simple guides already done to merge them at the same time.

Here is what is outstanding:
* Need to make the cards more responsive to small screens
* Need to change icons and make them more consistent and applicable (especially Polkadot and Parachain icons)
* Need to add a nice pink hue when you hover over the cards

Here is a screenshot:
Guide-Version2

If you have feedback on adding additional cards to this section, changing icons/icon recommendations or anything else please put a comment below.

### CODE REVIEW

**Comment by Juan-DiegoC** [comment]
I checked the CI and don't know why there is an error - do you know whats up?

**Comment by Swader** [comment]
You can ignore that one. @lsaether before you leave can you check what's wrong with the substrate check?
@EmilyOstbo @iggyweb3 can you look into syncing up the design with the overall feel of Polkadot's wiki? (@Juan-DiegoC it's not that we don't like yours, it's just that our hands are tied when doing visual changes to the wiki that significantly differ from the rest, so it's better to check).

**Comment by lsaether** [comment]
Substrate 3.0.0 was released yesterday and the Rust docs aren't updated yet. The error should say "Substrate has newer version but the rustdocs link does not exist."

**Comment by emresurmeli** [comment]
Please make sure to rebase master and check to see your changes are reflected locally before continuing work. We merged a new version of Docusaurus and have ran basic checks to see if it works, but could run into minor issues.

**Comment by jakehemmerle** [comment]
@EmilyOstbo @iggyweb3 can you checkout Bruno's above comment and give thumbs up?

**Pull request closed without merging**
