### PR TITLE
#1692 [Polkadot Guide Section: Initially Proposing to Exist on Getting Started Pages]

### LINKED ISSUE #1569: Create a Guides section
The section would contain all the getting started content + really simple guides on doing basic things. No technical explanations, just links to more complex versions of the guides (in learn / maintain / build). More picture-focused, where possible accompanied by video explainers. The guides section should be enough for a user to use ALL of Polkadot to its fullest extent, as much as "civilian" should be able to.

### PR DESCRIPTION
**Pull request by jakehemmerle**
#1692 

resolves #1569

### CODE REVIEW

**Comment by jakehemmerle** [comment]
waiting for CICD to checkout

**Comment by DannyS03** [comment]
Nice:) Other than maybe some of the To-Dos (https://github.com/w3f/polkadot-wiki/pull/1692#issue-571459310), LGTM

**Review by salmad3 — COMMENTED** [review]
Nice:) Other than maybe some of the To-Dos (https://github.com/w3f/polkadot-wiki/pull/1692#issue-571459310), LGTM.

We could probably use some newer (generic) icons or ask the team internally for a set

**Comment by salmad3** [comment]
After looking more into this, it seems the cards aren't configured in a way that is robust, as mentioned in the previous PR. 
We could also use assets (imgs, icons) from the polkadot.network site for the icons.

**Comment by salmad3** [comment]
The original proposal to have a polkadot guide would interrupt the purpose of the homepage, and I feel it doesn't sit too well as a doc. As a result, I decided to add the content with generic images for now on the getting started pages. 

image

image


The approach is to get something helpful out there, and then get together to decide general UX improvements as we could probably utilize react or the current docusaurus config to implement this on a "main page". We would also use icons as previously mentioned.

**Pull request merged**
