### PR TITLE
added link checker to CI

### PR DESCRIPTION
**Pull request by fgimenez**
Closes https://github.com/w3f/infrastructure/issues/62

### CODE REVIEW

**Comment by Swader** [comment]
This should check final links, not localhost - it's why it's failing right now.

**Review by Swader — CHANGES_REQUESTED** [review]
I am not sure how to make it check the final, resolved links, but it seems it can't check localhost (see CI fail)

**Comment by fgimenez** [comment]
Indeed, it builds the site from the PR, starts serving it locally and
crawls it; this way it can catch problems before they are deployed.

AFAIK it fails because of actual broken links, is that correct?

**Comment by fgimenez** [comment]
Regarding serving from localhost, the site source is not dependant on the domain it is served from, if you check the page source on any page under https://wiki.polkadot.network you will see that all the links don't have any reference to the domain, they look like `<a href="/docs/en/learn-introduction" target="_self">`

For instance, one 404 in the last CI build https://circleci.com/gh/w3f/polkadot-wiki/1206 is `/docs/es-ES/grants`, you can check that this link exists in https://wiki.polkadot.network/docs/es-ES/learn-introduction but the target page doesn't exist and redirects to home, the same as any non-existent page https://wiki.polkadot.network/docs/en/not-existing-page. This problem is now detected in CI, let me know if this is the expected behavior.

**Comment by Swader** [comment]
Indeed, looks like the translations aren't being built, thank you @fgimenez!

@ansonla3 if we add into CI the process of building the translations pages too, do we risk overwriting some of the translations-in-progress? We want to have a robust 404 detection in place, but we can't do it if the translation generator is lagging behind what's in the master language.

**Comment by ansonla3** [comment]
@fgimenez can you try again? 
@Swader it should be fine as long as we do not change the content inside the `translated_docs` directly.

**Comment by fgimenez** [comment]
> @fgimenez can you try again?

done, still 23 errors https://circleci.com/gh/w3f/polkadot-wiki/1227

**Comment by Swader** [comment]
@fgimenez I have merged the newest translations, let's try again please.

**Comment by fgimenez** [comment]
@Swader we are getting closer! only 6 errors now https://circleci.com/gh/w3f/polkadot-wiki/1250

**Comment by Swader** [comment]
Perfect, fixing!

**Comment by Swader** [comment]
@fgimenez all should be well now, except the translated files which still contain dead links. I'm wondering - do you have a way to run the crowdin bot and get it to send us a PR of the translations or was that something @ansonla3 set up?

**Comment by fgimenez** [comment]
Still 5 errors https://circleci.com/gh/w3f/polkadot-wiki/1253



> do you have a way to run the crowdin bot and get it to send us a PR of the translations or was that something @ansonla3 set up?

@ansonla3 worked on it, afaik the bot actually sends PRs, he can clarify :)

**Comment by Swader** [comment]
@fgimenez let's try again please

**Comment by fgimenez** [comment]
@Swader only 2 errors remaining! and both related to the same page https://circleci.com/gh/w3f/polkadot-wiki/1256

**Comment by Swader** [comment]
Once #235 is merged and crowdinbot submits another PR, we should be good.

**Comment by fgimenez** [comment]
Nice, one single failure after rebasing to master, looks like with the missing translation the build should pass https://circleci.com/gh/w3f/polkadot-wiki/1259

**Comment by Swader** [comment]
Crowdin bot got things pulled in. Time for the last test.

**Comment by fgimenez** [comment]
@Swader all green!! :tada:

**Comment by Swader** [comment]
Huzzah! @laboon @lsaether all in favor of adding this CI process to our main pipeline now?

**Comment by laboon** [comment]
let's do it!

**Comment by Swader** [comment]
@fgimenez please pull the trigger - not sure what else needs to be done but it's ready to be added as part of our regular pre-PR-merge pipeline!

**Comment by fgimenez** [comment]
:rocket: All is in place, we just need to merge

**Pull request merged**
