### PR TITLE
Gov Page Removed Broken Link

### LINKED ISSUE #3931: Governance docs broken link
In the [Governance docs](https://wiki.polkadot.network/docs/learn-governance#blacklisting) section blacklisting, the link to an example of an erroneous proposal is broken.

### PR DESCRIPTION
**Pull request by filippoweb3**

### CODE REVIEW

**Comment by filippoweb3** [comment]
@Szegoo I removed the link. The removal does not affect the overall meaning of the paragraph. Let me know if the change is OK for you.

**Comment by Szegoo** [comment]
@filippoweb3 Sure, it is fine with me.

**Review by DrW3RK — APPROVED** [review]

**Comment by DrW3RK** [comment]
Looks like Polkascan removed democracy section on their website. The same proposal can be viewed on other blockscanners or Polkassembly for reference https://polkadot.polkassembly.io/proposal/2

**Comment by DrW3RK** [comment]
I agree with @filippoweb3 in taking down the ref link, as it does not show any info about it being blacklisted

**Pull request merged**
