### PR TITLE
Update build-tools-index.md

### PR DESCRIPTION
**Pull request by vsofiya**
Add Chain IDE under IDEs section.

### CODE REVIEW

**Review by DrW3RK — APPROVED** [review]
Thank you

**Comment by vsofiya** [comment]
Thank you! 
Is there some reason why I don't see the update on https://wiki.polkadot.network/docs/build-tools-index?

**Comment by DrW3RK** [comment]
The changes to the Polkadot Wiki are deployed every 24 hours. This update should be live tomorrow. If this is time-sensitive, we can trigger a manual deployment.

**Comment by vsofiya** [comment]
It's not time-sensitive, thank you for the info

**Pull request merged**
