### PR TITLE
Update multisig-apps.md

### PR DESCRIPTION
**Pull request by jarvandev**
add mimir multisig wallet description

### CODE REVIEW

**Comment by DrW3RK** [comment]
Congratulations on winning the hackathons https://polkadot.polkassembly.io/post/2103

Does your app work on Polkadot network? I can only see an option to connect to Rococo on https://app.mimir.global/

**Comment by dioweb3** [comment]
Hi, I'm the Product Manager at Mimir. We have successfully completed our deployment on the Polkadot network. You're welcome to try it out: [app.mimir.global](https://app.mimir.global/)
@DrW3RK

**Comment by dioweb3** [comment]
Hello^^ Any feedback? @DrW3RK

**Comment by DrW3RK** [comment]
I may need to do something differently and could not get the wallet to work on Polkadot. Would your team be available for a call to discuss?

image

**Comment by dioweb3** [comment]
Hello, we do not include a web wallet, so you'll need to connect a plugin wallet first to use our service. We apologize that our UI did not provide the correct error message. Please refresh the page and click on the wallet connection area in the bottom left corner to connect your wallet for further operations. We hope this resolves your issue. If a meeting is needed to discuss further, you're welcome to choose a convenient time for you at https://calendly.com/tinyliu94/30min.

@DrW3RK 
Cc @jarvandev

**Comment by DrW3RK** [comment]
Thank you. I've tried importing my pre-existing multi-sig accounts but have not been successful. Compared to the other production-ready wallets on this Wiki doc, I'm afraid Mimir has some work to do. I scheduled a call for tomorrow to get a walk-through on Mimir. Looking forward to it.

image

**Comment by dioweb3** [comment]
See you tomorrow! I will give a proof of our work😊

**Comment by DrW3RK** [comment]
Thanks for the demo session! Very useful multisig product. Adding it to the Wiki.

**Review by DrW3RK — APPROVED** [review]

**Pull request merged**
