### PR TITLE
:memo: Add Basilisk finance as a chain that supports NFTs

### PR DESCRIPTION
**Pull request by vikiival**
Basilisk has the state-of-the-art implementation of uniques pallet and is a must to have it in docs.

### CODE REVIEW

**Review by DrW3RK — APPROVED** [review]
Thanks for the contribution!

**Comment by yangwao** [comment]
Hey @DrW3RK I don't see it live here https://wiki.polkadot.network/docs/learn-nft

What can be issue?

**Comment by DrW3RK** [comment]
@yangwao The content is live now. A CI job is scheduled each day to deploy the content to the website. I ran the job manually now.

**Comment by yangwao** [comment]
> I ran the job manually now.

thank you

**Pull request merged**
