### PR TITLE
Builds separate Kusama docs website

### PR DESCRIPTION
**Pull request by lsaether**
This looks huge because it does some re-arranging but actually only does a few things.

- Splits `website` directory into two directories, one `website` hosting the Polkadot Wiki and another `kusama-guide` hosting the Kusama guide.
- Moves all the scripts into a top level `script` directory (ex. inject, mirror, utils).
- Modifies the `siteConfig.js` of both `website` and `kusama-guide` to optionally build static versions (for IPFS) or the regular versions.
- Adds a copy script to move translated files from `website` to `kusama-guide`.
- Adds GitHub actions to deploy the sites to IPFS (Nothing fancy yet, DNSLink will come in a future PR).
- Modifies the `.circleci` script to use the new build process.

### CODE REVIEW

**Comment by ansonla3** [comment]
let me double-check what would happen for the translation before merging

**Comment by lsaether** [comment]
Translation should just continue to work with the pull requests to the `website` directory, we just need to copy this directory to kusama guide every time we build it.

**Comment by Swader** [comment]
Hesitant to click approve but LGTM so far. Will try and inspect more while I'm away - what's the process for building this locally and checking it out?

**Comment by ansonla3** [comment]
@lsaether I got the following error when starting. 

```
 npm start

> @ start /Users/anson/polkadot-wiki
> yarn mirror && docusaurus-start

yarn run v1.22.4
$ node scripts/mirror.js
✨  Done in 0.16s.
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '/Users/anson/polkadot-wiki/siteConfig.js'
Require stack:
- /Users/anson/polkadot-wiki/node_modules/docusaurus/lib/server/env.js
- /Users/anson/polkadot-wiki/node_modules/docusaurus/lib/start-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/anson/polkadot-wiki/node_modules/docusaurus/lib/server/env.js:13:20)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Module._compile (/Users/anson/polkadot-wiki/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Object.newLoader [as .js] (/Users/anson/polkadot-wiki/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1000:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/anson/polkadot-wiki/node_modules/docusaurus/lib/server/env.js',
    '/Users/anson/polkadot-wiki/node_modules/docusaurus/lib/start-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `yarn mirror && docusaurus-start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anson/.npm/_logs/2020-06-19T08_04_08_812Z-debug.log
```
do you know what's the problem?

**Comment by laboon** [comment]
I am getting the same error @lsaether , any ideas?

**Comment by lsaether** [comment]
Yeah I forgot to update the alias. There's now two scripts to start the respective docs sites `yarn kusma:start` and `yarn polkadot:start`, I updated the alias `yarn start` to be `yarn polkadot:start`.

**Comment by laboon** [comment]
This is from the Kusama page.  We should probably update the wording (s/Polkadot/Kusama/g) here and any other relevant pages.
Screen Shot 2020-06-19 at 2 28 40 PM

**Comment by laboon** [comment]
Or is that happening in a follow-up PR?

**Comment by lsaether** [comment]
@laboon Hm.. actually you shouldn't be seeing that page at all, it should direct you to kusam-index instead. Will look into it.

But yes, I didn't mention before but this PR right now is totally backwards compatible (in that it deploys the polkadot-wiki in exactly the same form) while we figure out the details of where to deploy the Kusama guide. I figure this PR could get merged first since it would lay out the new architecture, and we can follow up with a PR that does the Kusama guide deployment to a separate repository and also the IPFS domain linking.

**Review by ansonla3 — APPROVED** [review]
LGTM

**Comment by Swader** [comment]
Reviewing tonight or tomorrow morning

**Review by Swader — APPROVED** [review]

**Pull request merged**
