### PR TITLE
Enable crowdin for polkadot wiki only

### PR DESCRIPTION
**Pull request by nam-hle**
Another attempt after the failure of #2337.

### CODE REVIEW

**Review by salmad3 — APPROVED** [review]
LGTM

**Comment by salmad3** [comment]
Environment variables are updated now right?

**Comment by nam-hle** [comment]
No. I just changed the configuration of Crowdin Yaml file. I assume that @jakehemmerle set the right value that I gave.

Or can you please check that current CROWDIN_API_TOKEN starts with `b902dd`?

If this PR can not solved the issue, I will have no clues :( It works perfectly in my local environment

**Comment by salmad3** [comment]
@nam-hle reverted as CI didn't pass on master - seems like something with the token

**Pull request merged**
