### PR TITLE
Added fathom

### PR DESCRIPTION
**Pull request by Swader**
Let's see how fathom treats us for analytics. It's not a free service because it doesn't sell people's data. It's the ethical tradeoff we'd have to agree with. It's $140 per year, or $14 per month. Steep, but let's see if it's worth it?

### CODE REVIEW

**Comment by laboon** [comment]
Let me talk with finance, but I don't foresee a problem with such a small cost.

**Comment by Swader** [comment]
Let's get this in first during the 1-week trial, we can upgrade if we like it. The trial is already ongoing.

**Comment by laboon** [comment]
lgtm, let's try it

**Comment by ansonla3** [comment]
LGTM, but curious what is the difference between google analytics?

**Comment by Swader** [comment]
@ansonla3 GA is free but not private, fathom is private but not free. I.e. fathom is more into preserving privacy and more in line with our ethos of people owning their own data.

**Pull request merged**
