### PR TITLE
Fix kusama hijack

### LINKED ISSUE #289: Kusama section hijacks sidebar entries
When a major section includes a page ID also included by another major section, the former will lose that page in its menu. It gets overridden. See learn-identity. It's only visible in Kusama, not in Learn for Polkadot. This is probably the same for some other pages too.

### PR DESCRIPTION
**Pull request by lsaether**
closes #289

### CODE REVIEW

**Comment by Swader** [comment]
Can we add this to the CI so the mirroring is part of the build process and the mirrors are never out of date automatically? cc @fgimenez

**Comment by laboon** [comment]
pinging @fgimenez ^

**Comment by fgimenez** [comment]
Sorry, i totally missed this, so what should be done in CI?

**Comment by lsaether** [comment]
I think we'll be able to keep CI the same and use [husky](https://github.com/typicode/husky) to add a git hook that runs the script on every commit. It only registers a change in git if there is an actual diff to that file.

**Pull request merged**
