### PR TITLE
Update build-wallets.md

### PR DESCRIPTION
**Pull request by laboon**

### CODE REVIEW

**Comment by Swader** [comment]
But Parity Signer has no staking, it's just a signer, why would we say it has staking?

**Comment by laboon** [comment]
Well, if that's the case, the extension also doesn't allow staking. But people were confused because they thought you couldn't stake if you used PS.  What about changing it to "Allows indirect staking" or "Staking available via Polkadot-JS" or something?

**Comment by Swader** [comment]
I'd add columns:

- Native staking: Y/N
- Custom endpoints: Y/N

Then later add more like:

- Governance support: Y/N
- Treasury support: Y/N

etc...

**Comment by laboon** [comment]
Canceling this for a while, OBE anyways

**Pull request closed without merging**
