### PR TITLE
Update build-wallets.md

### PR DESCRIPTION
**Pull request by Yung-Beef**
These changes will help steer new entrants to the ecosystem away from the dreadful experience of using the polkadot.js extension as their substrate wallet. 

Treasury funded wallets were not endorsed, the W3F disclaimer is still there - it is merely noted that most community members prefer to use these wallets.

### CODE REVIEW

**Comment by filippoweb3** [comment]
dear @Yung-Beef thanks for this PR. We can't say "community members prefer" etc. It would be fine if you just note that "Polkadot-JS etc. are very powerful (and a good compromise between security and usability) but are also more complicated" or something along those lines.

**Comment by DrW3RK** [comment]
@Yung-Beef Thank you very much for the feedback! This is in line with the ongoing discussion within the team to improve the wallets page. Will share the Pull Request with those changes here later today and we welcome your feedback on it.

**Comment by Yung-Beef** [comment]
> dear @Yung-Beef thanks for this PR. We can't say "community members prefer" etc. It would be fine if you just note that "Polkadot-JS etc. are very powerful (and a good compromise between security and usability) but are also more complicated" or something along those lines.

Well the Polkadot.js extension is not very powerful, which is part of the problem. The .js apps are, but most users don't need to know that site even exists if they install a wallet that has good functionality.

**Comment by Yung-Beef** [comment]
Removed the "prefer" wording.

**Comment by arrudagates** [comment]
Why has this been stalled? Can we get a new review in this PR?

**Comment by DrW3RK** [comment]
@arrudagates This PR is high on our radar, and the underlying issue this PR highlights will be addressed once the whole team is back after the holidays. We will bring you and @Yung-Beef into the conversation when we create a PR that modifies the page.

To merge this PR as is, we have one issue - the wallets in the list are listed based on the chronological order of receiving the funds from the treasury. We see that this PR modifies it. I will revert that order now, and the PR will be ready to be merged.

**Review by DrW3RK — APPROVED** [review]

**Comment by arrudagates** [comment]
> @arrudagates This PR is high on our radar, and the underlying issue this PR highlights will be addressed once the whole team is back after the holidays. We will bring you and @Yung-Beef into the conversation when we create a PR that modifies the page.
> 
> To merge this PR as is, we have one issue - the wallets in the list are listed based on the chronological order of receiving the funds from the treasury. We see that this PR modifies it. I will revert that order now, and the PR will be ready to be merged.
> 
> 

Thank you for the quick response, I'm looking forward to discussing this more in depth, as in my opinion the underlying issue goes far beyond just the polkadot wiki, it actually highlights the struggle to join the ecosystem as a user, since unlike Ethereum, you can't just go to polkadot.network and find a handy list of all the available wallets to get started, which hinders adoption for the whole ecosystem!

**Comment by DrW3RK** [comment]
We are with you on this! Let's catch up after the holidays

**Comment by DrW3RK** [comment]
@Yung-Beef @arrudagates Here is the PR that improves the Wallets page. Please review https://github.com/w3f/polkadot-wiki/pull/4370

**Pull request merged**
