### PR TITLE
Enable Crowdin

### LINKED ISSUE #2333: Unable to access wiki docs in other languages
When we select other languages from dropdown menu on top right side of the website, it simply redirects to docs in English

### PR DESCRIPTION
**Pull request by nam-hle**
Continue #2213.

Resolve #2333, a part of #2294.

For maintainers, please help me config Github env variables for:

- CROWDIN_PROJECT_ID: it should be "371273"
- CROWDIN_API_TOKEN: generate a new one from your Crowdin profile https://support.crowdin.com/api/api-integration-setup/

### CODE REVIEW

**Review by salmad3 — APPROVED** [review]
LGTM

**Comment by nam-hle** [comment]
@DannyS03 Help me set up those env variables please

**Comment by DrW3RK** [comment]
I was able to add CROWDIN_PROJECT_ID to env variables. I do not have access to any profile on Crowdin. Does this have to be done by the owner of https://crowdin.com/project/polkadot-wiki ?

**Comment by jakehemmerle** [comment]
@nam-hle I added CROWDIN_API_TOKEN to the secrets; should be good to go. I did not regenerate the API key (for legacy purposes), so let me know if you need me to do that or it breaks or something weird. Thanks!

**Review by jakehemmerle — APPROVED** [review]

**Comment by nam-hle** [comment]
Hi guys, luckily I have a admin right for the Crowdin project. Do you accept to use my API token?

**Comment by jakehemmerle** [comment]
> Hi guys, luckily I have a admin right for the Crowdin project. Do you accept to use my API token?

sure go for it

rest of the team, from a security standpoint I don't see this as an issue since the token can be removed at any time and all information being used by crowdin for translations is public anyway

**Comment by nam-hle** [comment]
Please contact my Discord so I can send the key `nam-hle#6450`

**Comment by jakehemmerle** [comment]
> Please contact my Discord so I can send the key `nam-hle#6450`

@nam-hle Does the key I just added not work?

Can you contact me on matrix instead (@jake:web3.foundation ) ? I don't use discord and discord is not encrypted.

**Comment by nam-hle** [comment]
@jakehemmerle after all secret keys are setup, I think this PR can be merged.

**Comment by jakehemmerle** [comment]
@nam-hle for some reason this broke master when it was merged. Can you take a look and open a new PR?

https://github.com/w3f/polkadot-wiki/runs/3076656276 and
https://github.com/w3f/polkadot-wiki/runs/3075222113
were the builds

**Comment by nam-hle** [comment]
Hi @jakehemmerle, I also commented here. https://github.com/w3f/polkadot-wiki/issues/2333#issuecomment-880587358. Can you please take some time to confirm the correctness of secret keys as well as wrap the env variable name with quotes `"`, before I asked helps from Crowdin team?

**Comment by jakehemmerle** [comment]
> Hi @jakehemmerle, I also commented here. [#2333 (comment)](https://github.com/w3f/polkadot-wiki/issues/2333#issuecomment-880587358). Can you please take some time to confirm the correctness of secret keys as well as wrap the env variable name with quotes `"`, before I asked helps from Crowdin team?

yup, let me try that

**Comment by jakehemmerle** [comment]
@nam-hle I just added the variables with the quotes and it still failed. Here are the build fails:
https://github.com/w3f/polkadot-wiki/runs/3076966296
https://github.com/w3f/polkadot-wiki/runs/3076963454
https://github.com/w3f/polkadot-wiki/runs/3076963452

might be for different reasons than previously. Thanks for taking a look!

**Comment by nam-hle** [comment]
I suffered the same issue before. I follow the instructions here.
https://github.com/crowdin/crowdin-cli/issues/336#issuecomment-866842739.

The difference in kusama guide should be fixed if Crowdin issue in polkadot wiki is resolved. I will take the responsibility on kusama guide later.

**Pull request merged**
