### PR TITLE
Resolve duplicate dependency issue with @polkadot/util and @polkadot/util-crypto

### PR DESCRIPTION
**Pull request by alfarok**
This PR address #3446.

I upgraded `@polkadot/util` and `@polkadot/util-crypto` in the package.json file to allow up to the latest released version which is 9.6.2 for both.  After clearing my existing node modules and re-running `yarn install`, the duplicate dependencies are removed (dropping version 8.2.2 for both).  Running `yarn polkadot:start` no longer shows the duplicate errors outlined in #3446.

### CODE REVIEW

**Comment by alfarok** [comment]
Please let me know if anyone is aware of a legacy reason the two versions were used.  Everything appeared to build and function locally with the updated dependency tree but I will double check the functionality referenced in `addressChanger.js` tomorrow.  I believe this is the only location these modules are used.

**Comment by DrW3RK** [comment]
I remember we had issues previously with address changer https://github.com/w3f/polkadot-wiki/issues/2415
In fact, we have stopped using it. The address convertor tool used to be here previously https://wiki.polkadot.network/docs/learn-accounts#address-conversion-tools

So, yeah. Nothing to worry about I guess!

**Comment by alfarok** [comment]
Thanks for the link, it does look like it was remove but is still present in the translated docs in the repo.  I am not exactly sure how translations are handled.  

I am guessing that the address changer inline tool is present but broken in the translated versions.  I want to make sure swapping the dependency version doesn't cause any errors in those versions that still load `@polkadot/util` and `@polkadot/util-crypto` modules.

Example:
https://github.com/w3f/polkadot-wiki/blob/master/polkadot-wiki/translated_docs/it/learn-accounts.md#address-conversion-tools

@DrW3RK Do you know how I can view a translated version on localhost, such as:

http://localhost:3000/translated_docs/it/learn-accounts.md#address-conversion-tools

Since these modules aren't doing anything right now the solution might be to remove them completely after removing the translated references.

**Comment by DrW3RK** [comment]
We have had problems with Translated docs as well in the past and it might make sense to reimplement that functionality from scratch. @emresurmeli do you have any input on this?

**Review by DrW3RK — APPROVED** [review]

**Pull request merged**
