### PR TITLE
Update learn-DOT.md

### PR DESCRIPTION
**Pull request by gavinly**

### CODE REVIEW

**Comment by Swader** [comment]
Thanks! Could you run prettier on this to fix format please? `npx prettier --write [file]`

**Comment by gavinly** [comment]
@Swader I'm not technically-inclined enough to do that easily. I'm just familiar with editing from the Github website.

**Comment by laboon** [comment]
@krichard410 can you pull down this branch, run prettier, and push back up?

**Comment by krichard410** [comment]
@laboon Should be good to go!

**Comment by Swader** [comment]
Hmm, our CI failed to run on this push again. @fgimenez any ideas why this happens?

**Comment by fgimenez** [comment]
> Hmm, our CI failed to run on this push again. @fgimenez any ideas why this happens?

@Swader this is the last failed build https://circleci.com/gh/w3f/polkadot-wiki/9422 
```
$ npm i prettier
node_modules/.bin/prettier -c docs/*.md
npm WARN saveError ENOENT: no such file or directory, open '/home/circleci/project/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/circleci/project/package.json'
npm WARN project No description
npm WARN project No repository field.
npm WARN project No README data
npm WARN project No license field.

+ prettier@2.0.5
added 1 package from 1 contributor and audited 1 package in 0.539s
found 0 vulnerabilities

Checking formatting...
docs/learn-DOT.md
Code style issues found in the above file(s). Forgot to run Prettier?

Exited with code exit status 1
```

I think the npm warnings should be fine bc looks like prettier is installed at the end, but later there's `Code style issues found in the above file(s). Forgot to run Prettier?` looks like this is what makes the build fail.

**Comment by Swader** [comment]
Right but @krichard410 push to fix the style was not CI-ed. Does CI ignore pushes to branches that come from non-author?

**Comment by fgimenez** [comment]
They should not be ignored AFAIK but indeed it was not triggered after this commit https://github.com/w3f/polkadot-wiki/pull/583/commits/555468e706e8512148c84490be2301c1e16c25ec 

This is an external branch and @krichard410 pushed to it right? can we try again with an empty commit? Something like `git commit -m"trigger CI?" --allow-empty && git push`

**Review by lsaether — APPROVED** [review]

**Pull request merged**
