### PR TITLE
add dotscanner to tools

### PR DESCRIPTION
**Pull request by Deekor**

### CODE REVIEW

**Comment by salmad3** [comment]
Should wait until scanner is more feature-rich (as compared to the other ones listed) E.g. shows extrinsics

**Comment by Deekor** [comment]
Extrinsics are now supported. And the council has approved more features: https://kusama.polkassembly.io/motion/324

**Comment by Deekor** [comment]
@DannyS03 can we please reopen now?

**Comment by salmad3** [comment]
Good call - saw the updates on matrix too:) Will get the team to review it

**Comment by Deekor** [comment]
> Good call - saw the updates on matrix too:) Will get the team to review it 

Thanks!

**Review by salmad3 — APPROVED** [review]

**Pull request merged**
