### PR TITLE
Wiki Reorg: Unify Param Page

### PR DESCRIPTION
**Pull request by filippoweb3**
Put Kusama info into the Polkadot page in the maintain section.

Mostly migrating content and removing Council and Tech Committee info. Further factual incorrect things can be addressed in a following PR.

### CODE REVIEW

**Comment by filippoweb3** [comment]
Redirect works on staging.

**Review by DrW3RK — APPROVED** [review]

**Comment by DrW3RK** [comment]
Looks good. I have not checked the render though. @CrackTheCode016 Could you cross check this? Can merge after Bader's approval.

**Review by CrackTheCode016 — CHANGES_REQUESTED** [review]
Looks great!  One thing - the "Accounts, Identity and Crowdloans" needs a tabbed setup like the others.  It renders fine on my end after running locally.

Also - there was a merge conflict, I believe it's fine now, would be good to test on staging before merge just to be sure.

**Comment by filippoweb3** [comment]
@CrackTheCode016 the "Accounts, Identity and Crowdloans" part has conditional rendering. I added the tabs only for tables where the conditional rendering does not work. Will add tabs later on when we remove the conditional rendering :)

**Comment by filippoweb3** [comment]
staging tested, all good

**Pull request merged**
