### PR TITLE
Fast Unstake is live on Polkadot

### PR DESCRIPTION
**Pull request by DrW3RK**

### CODE REVIEW

**Review by filippoweb3 — APPROVED** [review]
lgtm, should we just remind the reader that fast unstaking applies only to nominators and not to pool members?

**Comment by DrW3RK** [comment]
Yes, let's state it explicitly. What would be the best way? Adding a separate note in nomination pools doc or modify the existing note here? To keep things simple, we can do it in a different PR.

**Comment by filippoweb3** [comment]
Agree, we can do it in another PR. Not sure of the pool page already states that fast unstake is not possible. If not, we can probably add it there and say in the "non-pool" pages that fast unstake is possible only for nominators and not pool members. What do you think?

**Comment by DrW3RK** [comment]
sounds good. merging this

**Pull request merged**
