### PR TITLE
Wiki Reorg: Transfers Category Sidebar

### PR DESCRIPTION
**Pull request by filippoweb3**
See [this issue](https://github.com/w3f/polkadot-wiki/issues/4376) and [this google doc](https://docs.google.com/document/d/1Fl8ReBIzcaQEOyF6s03d7MEcgk8aTVEt7xjmzAk_k5I/edit) for more information about the Wiki reorg.

### CODE REVIEW

**Review by DrW3RK — COMMENTED** [review]
Just one nit - Not all extrinsics are transfers. It would be better to leave it where it is.

**Comment by filippoweb3** [comment]
Yeah, I was struggling to pick a name for that section but I think is good to have it separated from accounts, also because other pages fit well in there. What do you suggest? Transactions? Something that the user can easily understand as extrinsic is something that is not understandable without reading the pages. IMO extrinsics page does not fit well in Accounts. We even mention extrinsics (aka types of transactions). My point is that technically speaking "Transactions" or "Transfer" is not 100% right but it drives the reader in the right place to learn about extrinsics.

**Comment by filippoweb3** [comment]
@DrW3RK I moved the Extrinsic page to General as it contains important security information.

**Comment by DrW3RK** [comment]
If you renamed it from "Transfers" to "Transactions", I think it fits very well. Let me move it in there

**Comment by DrW3RK** [comment]
If you think that the security-related info on the extrinsics page is well suited to be on the scams page or dyor page, that content can be moved there, and then we can point to that section in this doc.

Having Extrinsics, Balance Transfers and Transaction fees under the "Transactions" folder is apt.

**Review by DrW3RK — APPROVED** [review]

**Pull request merged**
