### PR TITLE
Add GetBlock RPC Provider to Polkadot tools

### PR DESCRIPTION
**Pull request by JoGetBlock**
Shared Nodes https://getblock.io/nodes/dot/
Dedicated Nodes https://getblock.io/dedicated-nodes/dot/

### CODE REVIEW

**Comment by filippoweb3** [comment]
@JoGetBlock, the nodes are not listed on the [Polkadot JS Apps](https://polkadot.js.org/apps/#/explorer), did you receive a treasury fund? If yes, can you provide evidence?

**Comment by JoGetBlock** [comment]
> @JoGetBlock, the nodes are not listed on the [Polkadot JS Apps](https://polkadot.js.org/apps/#/explorer), did you receive a treasury fund? If yes, can you provide evidence?

Can we add GetBlocks Polkadot endpoints there? There was no treasury, Polkadot support manager said that we could add our Nodes to the list as a partner service providing RPC nodes

**Comment by DrW3RK** [comment]
Hey @JoGetBlock Thank you very much for contributing to the Wiki. As you can notice on the page, the Wiki lists only public and open-source tools. It does not list commercial services requiring a subscription, fees, or other payment. We will also get this note added to the docs so there will not be any ambiguity. If you have any public RPC endpoint, we are happy to list it.

**Comment by JoGetBlock** [comment]
> Hey @JoGetBlock Thank you very much for contributing to the Wiki. As you can notice on the page, the Wiki lists only public and open-source tools. It does not list commercial services requiring a subscription, fees, or other payment. We will also get this note added to the docs so there will not be any ambiguity. If you have any public RPC endpoint, we are happy to list it.

@DrW3RK  We have shared nodes which is a daily free pack of requests, but with faster response time. 
Indeed we don't actually offer what you call Public Infrastructure, though can we discuss the possibility deploying Public Solution for Polkadot? Is it possible to create a telegram chat to discuss this?

**Comment by JoGetBlock** [comment]
@DrW3RK  Can we discuss possibility deploying Public Solution for Polkadot? Is it possible to create a telegram chat to discuss this?

**Comment by DrW3RK** [comment]
I'm forwarding your request to Web3 Foundation. Please share your contact details at radha@web3.foundation

**Comment by JoGetBlock** [comment]
> I'm forwarding your request to Web3 Foundation. Please share your contact details at [radha@web3.foundation](mailto:radha@web3.foundation)

Wrote to this gmail, got no answer yet, my gmail joan@getblock.io

**Comment by DrW3RK** [comment]
Hey @JoGetBlock You should have received the response now. Just FYI, most of the team is now at SXSW conference and the response rate will be slow. Thanks for your patience!

**Comment by DrW3RK** [comment]
Happy to reopen the PR once a public RPC node is deployed. Closing the PR for now.

**Pull request closed without merging**
