### PR TITLE
Updated FAQ page

### PR DESCRIPTION
**Pull request by krichard410**
I moved the FAQ page underneath the Main section for easier access and updated some grammar

### CODE REVIEW

**Comment by lsaether** [comment]
Can you check your [git configuration](https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration)? Specifically that the email matches with the one you have on GitHub, I'm starting to think maybe this is the reason it won't run the CI on your commits - that the commits come from a non-GH committer (hence the blank profile pic on the commit messages). 

image

Just a guess

**Comment by Swader** [comment]
Hmm I think the translated files and menus should not be in this PR, they should be part of the build process. Can you confirm @lsaether?

**Comment by lsaether** [comment]
Translated files will be kept in sync by the [Crowdin bot](https://github.com/w3f/polkadot-wiki/pull/607). There's no need to include the files because the bot will update them in a few minutes after changes are merged to master.

**Comment by Swader** [comment]
@krichard410 can you clean up this PR by removing all the files not related to the FAQ?

**Comment by krichard410** [comment]
> @krichard410 can you clean up this PR by removing all the files not related to the FAQ?

Sure! By translated files, do you mean the .json ones? @Swader

**Comment by Swader** [comment]
Everything with `i18n` or `translated_docs` in the filepath

**Comment by Swader** [comment]
@krichard410 looks like a link borked

```
URL        `learn-faq#what-are-the-ways-to-find-out-the-minimum-stake-necessary-for-the-validators'
Name       `here'
Parent URL http://localhost:3000/docs/en/maintain-guides-how-to-validate-kusama, line 38, col 1
Real URL   http://localhost:3000/docs/en/learn-faq#what-are-the-ways-to-find-out-the-minimum-stake-necessary-for-the-validators
Check time 0.977 seconds
Size       156B
Result     Error: 404 Not Found
 5 threads active,     0 links queued, 1139 links in 1155 URLs checked, runtime 41 seconds
```

**Comment by Swader** [comment]
Huh, two more. Guide.kusama.network is definitely dead and shouldn't be linked to.

```
URL        `https://guide.kusama.network/en/latest/try/validate/#set-the-session-key'
Name       `Kusama guide'
Parent URL http://localhost:3000/docs/en/maintain-guides-secure-validator, line 108, col 1
Real URL   https://guide.kusama.network/en/latest/try/validate/#set-the-session-key
Check time 1.635 seconds
Size       291B
Result     Error: 404 Not Found

URL        `https://guide.kusama.network/en/latest/try/nicks/'
Name       `set a nick'
Parent URL http://localhost:3000/docs/en/maintain-guides-how-to-join-council, line 112, col 36
Real URL   https://guide.kusama.network/en/latest/try/nicks/
Check time 1.613 seconds
Size       291B
Result     Error: 404 Not Found
 2 threads active,     0 links queued, 1153 links in 1164 URLs checked, runtime 41 seconds
```

**Comment by krichard410** [comment]
> Huh, two more. Guide.kusama.network is definitely dead and shouldn't be linked to.
> 
> ```
> URL        `https://guide.kusama.network/en/latest/try/validate/#set-the-session-key'
> Name       `Kusama guide'
> Parent URL http://localhost:3000/docs/en/maintain-guides-secure-validator, line 108, col 1
> Real URL   https://guide.kusama.network/en/latest/try/validate/#set-the-session-key
> Check time 1.635 seconds
> Size       291B
> Result     Error: 404 Not Found
> 
> URL        `https://guide.kusama.network/en/latest/try/nicks/'
> Name       `set a nick'
> Parent URL http://localhost:3000/docs/en/maintain-guides-how-to-join-council, line 112, col 36
> Real URL   https://guide.kusama.network/en/latest/try/nicks/
> Check time 1.613 seconds
> Size       291B
> Result     Error: 404 Not Found
>  2 threads active,     0 links queued, 1153 links in 1164 URLs checked, runtime 41 seconds
> ```

Hm..where should these links be redirected to? @Swader

**Comment by Swader** [comment]
If they have no counterpart in the modern wiki, they and the relevant subsections can just be removed. For example, the nicks module is long dead, there's nothing to try there

**Comment by Swader** [comment]
Good job!

**Pull request merged**
