### PR TITLE
Update the Fearless Wallet set of features

### PR DESCRIPTION
**Pull request by SkyForger79**
The set of features has been integrated in terms of the Kusama Treasury Grant #5.
Link to the proposal: https://kusama.polkassembly.io/treasury/178

Final Demos are available here:
https://www.youtube.com/watch?v=8ZmeotlaTHU
https://www.youtube.com/watch?v=4rK1rN1TeKA&t=3s

Actual build with the declared functionality are on the markets: https://apps.apple.com/us/app/fearless-wallet/id1537251089 https://play.google.com/store/apps/details?id=jp.co.soramitsu.fearless

### CODE REVIEW

**Review by DrW3RK — APPROVED** [review]
Thank you!

**Comment by DrW3RK** [comment]
Just FYI, there will be an update to the wallets page. Context: https://github.com/w3f/polkadot-wiki/pull/4161

We will loop you in on the PR, when it is live on the repo

**Comment by SkyForger79** [comment]
Thanks for the update and support. 
Let's keep in touch with the upcoming update of the page.

**Comment by DrW3RK** [comment]
@SkyForger79 Here is the PR that improves the Wallets page. Please review https://github.com/w3f/polkadot-wiki/pull/4370

**Pull request merged**
