### PR TITLE
Pdf export

### PR DESCRIPTION
**Pull request by Swader**
Solves #63 

There are two new commands: `kusama:pdf` and `polkadot:pdf`. They generate `kusama-guide/static/kusama-wiki.pdf` and `website/static/polkadot-wiki.pdf` respectively. These commands take a while to execute and need to run against a locally running wiki, so they're not part of any other command just now. They feel a bit naked without a ToC front page, so that's up next along with the other stuff below.

Please test.

To do:

- [x] Add link to download on pages
- [ ] Build ToC front page
- [ ] Add export process to circle build

### CODE REVIEW

**Comment by lsaether** [comment]
I would recommend adding a GitHub action ([example](https://github.com/w3f/polkadot-wiki/blob/master/.github/workflows/check-substrate-release.yml)) to export the PDF on push to master, then it can publish it to the releases assets.

**Comment by lsaether** [comment]
Why not use a [markdown to pdf parser](https://md2pdf.netlify.app/)?

That would come up with cleaner end renders.

**Review by krichard410 — COMMENTED** [review]
This is neat! I'm excited to see the ToC page. 
Just wondering though if the 'accept cookies' bar could be removed when the pdf has downloaded, as it covers up part of the content on the page. I'm also wondering if it's possible to remove the header and footer navigation if the page continues onto the next. The navigation on each page covers up some of the images/material that is there. 
It might also be good too if blank pages were removed, as they aren't really necessary.
For the download button that will be on each page, will there also be an option to download the whole site? or is it page by page?

**Comment by Swader** [comment]
> @lsaether: I would recommend adding a GitHub action (example) to export the PDF on push to master, then it can publish it to the releases assets.

Sounds good, was planned, but need to iron out the output first.

> @lsaether: That would come up with cleaner end renders.

Cleaner in which way?

> @krichard410 'accept cookies' ... header and footer navigation

None of those should be showing - the print CSS has been modified to remove them. Let me check what's up...

Download would be full book only, did not consider page by page (seems pointless).

**Comment by Swader** [comment]
Looks like I forgot to `git add` the main CSS file. Done now, please re-test for cleaner output.

**Comment by krichard410** [comment]
Just re-tested it, it looks great. Could we also get the page numbers in there too?

**Comment by krichard410** [comment]
One thing I noticed were these unlinked images on the Kusama Governance page. Could these be fixed?

Screen Shot 2020-08-18 at 12 04 51 PM

**Comment by krichard410** [comment]
Is there a way to remove embedded videos from the pdf format (and replace them with the link)? I saw them throughout both pdfs, but it seems a bit pointless to have them in there since they don't actually play.

**Comment by Swader** [comment]
Yes, that'll need tweaks. It's a matter of modifying the CSS for print style so that it hides an embed and shows a video, same for the formula images above I assume. I'll try and get that polished. Thanks for testing!

**Comment by Swader** [comment]
Ok, so the entire flow works now, but the problem with Github Actions is that one workflow cannot `needs` another workflow. So I can't build the PDF in one workflow and the use it the deploy workflow - I'll need to modify the two deploys. Working on that now. Hopefully they add dependency actions soon.

**Comment by Swader** [comment]
I have no way to check if this passes now. @lsaether any ideas? This triggers on commits to master only and *should* work, but not sure how to test. Tried [act](https://github.com/nektos/act) but it doesn't work without netcat, and I'm not sure how to make sure the container that runs the workflow gets it. Experimenting...

Edit: [ah, drat](https://stackoverflow.com/questions/57982945/how-to-apt-get-install-in-a-github-action).

**Comment by Swader** [comment]
Ok, I recommend trying to merge this and seeing what happens, then reverting what doesn't work. All in favor @lsaether @ansonla3?

**Comment by Swader** [comment]
Unless there are any objections I'm merging this tonight and seeing what blows up.

**Pull request merged**
