### PR TITLE
do not require check-links for deploying

### LINKED ISSUE #251: Remove translated docs from link-checking
@fgimenez can you please set up the CI so that it doesn't take translated docs into account? As it is, all our PRs will auto-fail when we add new pages, and it doesn't make sense to wait for the crowdin bot to do a PR after every submit of ours. Since the crowdin PR is automated, it will by default inherit good and bad links from the main docs, so it doesn't make much sense to check those anyway.

### PR DESCRIPTION
**Pull request by fgimenez**
Closes https://github.com/w3f/polkadot-wiki/issues/251

### CODE REVIEW

**Comment by Swader** [comment]
Great! Is it hard to update the CI setup to not check translated docs for links so we can solve both things at once?

**Comment by fgimenez** [comment]
If there's a concrete path to be ignored then it can be done pretty easily, for example `docs/zh-CN/` ?

**Comment by Swader** [comment]
Anything NOT under /en/ should be ignored. So docs/en/ yes, docs/anything-else/ no.

**Comment by fgimenez** [comment]
Ok pls take a look, now the crawler starts in /docs/en and only reaches 1 level (bc there are links to, for instance, /docs/zh-CN from /docs/en), let me know wdyt

**Comment by Swader** [comment]
Looks good to me!

**Review by Swader — APPROVED** [review]
Let's get this in - will it also break due to failing CI before this non-fail CI is merged in?

**Comment by fgimenez** [comment]
> Let's get this in

Ok, done. There were still some 404 linked from `/docs/en/`, pls check https://circleci.com/gh/w3f/polkadot-wiki/1308

> will it also break due to failing CI before this non-fail CI is merged in?

All the branches forked off master from now on will have the fi in place, the existing branches need to rebase and push to refresh `.circleci/config.yml`

**Comment by Swader** [comment]
Thanks!

**Pull request merged**
