### PR TITLE
Subtract should be plus in total balance

### PR DESCRIPTION
**Pull request by laboon**

### CODE REVIEW

**Comment by laboon** [comment]
See here if you don't believe me =)

https://github.com/paritytech/substrate/blob/eb9033b826b9e8115c20707fe66af0ceb177e99c/frame/balances/src/lib.rs#L42

**Comment by wischli** [comment]
Thanks! We were really confused by the Wiki entry.

**Comment by salmad3** [comment]
Just need to resolve conflicts caused by: https://github.com/w3f/polkadot-wiki/pull/2145

**Comment by tjwelde** [comment]
The Pr seems to want the same as we wanted to achieve with #2145. So if @laboon doesn't want to change wording, I think we can close this.

**Comment by salmad3** [comment]
> The Pr seems to want the same as we wanted to achieve with #2145. So if @laboon doesn't want to change wording, I think we can close this.

Can confirm that PR changes satisfy the same change in this PR - will close as duplicate.

**Pull request closed without merging**
