### PR TITLE
Update substrate docs

### LINKED ISSUE #745: Linking to tags across parity resources
From danforbes:

From my POV, I just want to suggest that you have alignment among the resources you're linking to. Personally, I think it is always best to link to the latest tagged released, but if this is not possible, linking to master is fine too. If you decide to link to tagged versions, Rustdocs links should go to to substrate.dev/rustdocs, if you're linking to master use crates.parity.io.

### PR DESCRIPTION
**Pull request by lsaether**
closes #745 

- [X] Updates to tagged release and changes crates.parity.io -> substrate.dev.
- [X] Adds CI check for latest release.

### CODE REVIEW

**Comment by ansonla3** [comment]
looks good.

**Review by krichard410 — COMMENTED** [review]
What are the steps to test this? =)

**Comment by Swader** [comment]
Run `node scripts/check-substrate-release.js`

**Comment by lsaether** [comment]
The CI already runs for this branch

image

**Review by Swader — APPROVED** [review]

**Review by krichard410 — APPROVED** [review]
Looks good to push to master !

**Pull request merged**
