### PR TITLE
Add KodaDot Video about minting NFTs

### PR DESCRIPTION
**Pull request by filippoweb3**

### CODE REVIEW

**Comment by filippoweb3** [comment]
@helloitsdamsky please review this PR :)

**Comment by damskyftw** [comment]
Looks good, but does it render ok for you in the preview?
image

**Comment by filippoweb3** [comment]
@helloitsdamsky it renders ok
Screenshot 2023-09-11 at 11 54 39

**Comment by damskyftw** [comment]
Alright, this is good by me! Thanks @filippoweb3

**Review by DrW3RK — APPROVED** [review]

**Pull request merged**
