### PR TITLE
Update Validator Pages

### LINKED ISSUE #2147: Update Validator Based Pages
- https://wiki.polkadot.network/docs/en/maintain-guides-secure-validator
- https://wiki.polkadot.network/docs/en/maintain-guides-how-to-validate-polkadot
- https://wiki.polkadot.network/docs/en/maintain-guides-how-to-upgrade

### PR DESCRIPTION
**Pull request by salmad3**
Resolves #2147

### CODE REVIEW

**Comment by salmad3** [comment]
I assume that [Signing Outside the Client](https://wiki.polkadot.network/docs/en/maintain-guides-secure-validator#signing-outside-the-client) is still a work in progress: https://github.com/paritytech/substrate/issues/4689

**Comment by salmad3** [comment]
Content wise any insight on things that need to be updated or added + best practices would be great.

**Comment by michaelmowry** [comment]
It looks like the first link under "How Many KSM Do I Need?" is broken on this page https://guide.kusama.network/docs/mirror-maintain-guides-how-to-validate-kusama/#validate

**Comment by lamafab** [comment]
In general, LGTM.

## maintain-guides-how-to-validate-polkadot.md

> Warning: It is highly recommended that you have significant system administration experience before attempting to run your own validator.

Make this warning stand out more. You might also want to add something along the lines of  _"You must be able to handle unexpected technical issues and anomalies with your node which you must be able to fix yourself. Being a validator involves more than just executing the Polkadot binary."_

I've had painful experiences with some community members which were running a validator and had almost no technical experience...

> Any instances of non-compliance with the consensus algorithms result in punishment by removal of some **or all of the validator’s staked DOT**

Are you sure about the "all" part?

> Building and Installing the polkadot **Binary**

Binary should be lowercase, "binary"

Also, the way this guide is structured it seems like installing Rust and compiling from source is the requirement to validate. IMO the compilation steps should not be shown at all here, I'd move it all into a separate guide and just refer to it. Ideally you should present the reader with two options: _[download and run the binary directly](https://github.com/paritytech/polkadot/releases) or build from source, as shown in guide *X*_. Wdyt?

## learn-validator.md

Might be useful to explain what "Relay Chain" means exactly, but I'm not sure if this is appropriate here.

**Comment by salmad3** [comment]
> In general, LGTM.
> 
> ## maintain-guides-how-to-validate-polkadot.md
> > Warning: It is highly recommended that you have significant system administration experience before attempting to run your own validator.
> 
> Make this warning stand out more. You might also want to add something along the lines of _"You must be able to handle unexpected technical issues and anomalies with your node which you must be able to fix yourself. Being a validator involves more than just executing the Polkadot binary."_
> 
> I've had painful experiences with some community members which were running a validator and had almost no technical experience...
> 
> > Any instances of non-compliance with the consensus algorithms result in punishment by removal of some **or all of the validator’s staked DOT**
> 
> Are you sure about the "all" part?
> 
> > Building and Installing the polkadot **Binary**
> 
> Binary should be lowercase, "binary"
> 
> Also, the way this guide is structured it seems like installing Rust and compiling from source is the requirement to validate. IMO the compilation steps should not be shown at all here, I'd move it all into a separate guide and just refer to it. Ideally you should present the reader with two options: _[download and run the binary directly](https://github.com/paritytech/polkadot/releases) or build from source, as shown in guide _X__. Wdyt?
> 
> ## learn-validator.md
> Might be useful to explain what "Relay Chain" means exactly, but I'm not sure if this is appropriate here.

> In general, LGTM.
> 
> ## maintain-guides-how-to-validate-polkadot.md
> > Warning: It is highly recommended that you have significant system administration experience before attempting to run your own validator.
> 
> Make this warning stand out more. You might also want to add something along the lines of _"You must be able to handle unexpected technical issues and anomalies with your node which you must be able to fix yourself. Being a validator involves more than just executing the Polkadot binary."_
> 
> I've had painful experiences with some community members which were running a validator and had almost no technical experience...
> 
> > Any instances of non-compliance with the consensus algorithms result in punishment by removal of some **or all of the validator’s staked DOT**
> 
> Are you sure about the "all" part?
> 
> > Building and Installing the polkadot **Binary**
> 
> Binary should be lowercase, "binary"
> 
> Also, the way this guide is structured it seems like installing Rust and compiling from source is the requirement to validate. IMO the compilation steps should not be shown at all here, I'd move it all into a separate guide and just refer to it. Ideally you should present the reader with two options: _[download and run the binary directly](https://github.com/paritytech/polkadot/releases) or build from source, as shown in guide _X__. Wdyt?
> 
> ## learn-validator.md
> Might be useful to explain what "Relay Chain" means exactly, but I'm not sure if this is appropriate here.

Thanks @lamafab. Regarding the comment on creating a new guide that separates compilation, I see what you mean. It could also relate to https://wiki.polkadot.network/docs/maintain-sync/. Any thoughts @wpank @laboon?

**Comment by salmad3** [comment]
> It looks like the first link under "How Many KSM Do I Need?" is broken on this page https://guide.kusama.network/docs/mirror-maintain-guides-how-to-validate-kusama/#validate

Thanks @michaelmowry. There has been a new version released for the wiki and some hiccups that which resulted in some broken links, which is currently being addressed.

**Comment by salmad3** [comment]
We can discuss additional page for compilation steps soon. Would like to get the pages updated in the meantime. 

Going to merge as feedback has been addressed. Will drop a note in the validator channels again for any folks that would like to see something added/changed.

**Pull request merged**
