### PR TITLE
Adds Snowbridge library dependency

### PR DESCRIPTION
**Pull request by claravanstaden**
Corrects the fact that Snowbridge relies on a library for BLS signature verification.

### CODE REVIEW

**Comment by claravanstaden** [comment]
Hey @filippoweb3! I made a small change to the bridges comparison table.

Additionally, I would like to know if this is truly accurate?

> Low latency, 5-7 minutes on reference hardware.

 As far as I know, Hyperbridge is bounded by the same constraints as Snowbridge - latency is dictated by the source chain finality mechanism, so if Ethereum takes 2 epochs to finalize, it would be the same latency for all trustless bridges.

**Comment by filippoweb3** [comment]
hey @claravanstaden I remember Seun telling me that Hyperbridge has that latency because it does not use random sampling beefy but ZK circuits

**Comment by claravanstaden** [comment]
> hey @claravanstaden I remember Seun telling me that Hyperbridge has that latency because it does not use random sampling beefy but ZK circuits

That would be Polkadot to Ethereum direction. Ethereum to Polkadot latency would be longer iiuc.

**Comment by seunlanlege** [comment]
> Additionally, I would like to know if this is truly accurate?

This is in the Polkadot -> Ethereum direction, both snowbridge & Hyperbridge should have the same latency in the Ethereum to Polkadot direction.

**Comment by filippoweb3** [comment]
@seunlanlege got it I will create a PR to correct that fact

**Review by filippoweb3 — APPROVED** [review]
thanks for this contribution! :D

**Pull request merged**
