### PR TITLE
Fix injections

### LINKED ISSUE #2443: Fix Injections
Injects don't seem to be working properly

### PR DESCRIPTION
**Pull request by nam-hle**
Fixes #2443.

Our injection syntax may be conflicts with emphasis Markdown syntax, so I suggest changing emphasis from `_some thing_` into `*some thing*` if the conflict happens.

### CODE REVIEW

**Comment by salmad3** [comment]
Thanks @nam-hle! We ran into an issue with the CI (and also running locally) 
```
yarn add v1.22.11
[1/4] 🔍  Resolving packages...
error Received malformed response from registry for "docusaurus-preset-name". The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

```
error An unexpected error occurred: "https://registry.yarnpkg.com/docusaurus-preset-name/-/docusaurus-preset-name-1.0.0.tgz: Request failed \"404 Not Found\"".
```

Are you able to run locally?

**Comment by salmad3** [comment]
registry may be down but perhaps the request isn't going through because of some restriction or authentication that changed

**Comment by nam-hle** [comment]
> Thanks @nam-hle! We ran into an issue with the CI (and also running locally)
> 
> ```
> yarn add v1.22.11
> [1/4] 🔍  Resolving packages...
> error Received malformed response from registry for "docusaurus-preset-name". The registry may be down.
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
> ```
> 
> ```
> error An unexpected error occurred: "https://registry.yarnpkg.com/docusaurus-preset-name/-/docusaurus-preset-name-1.0.0.tgz: Request failed \"404 Not Found\"".
> ```
> 
> Are you able to run locally?

Yes it works on my local :(

**Comment by DannyS03** [comment]
Lets merge it into master as we can stage it on staging.polkadot.network, but first need to figure out the issue with `docusaurus-preset-name"`
It seems it was even removed: https://www.npmjs.com/package/docusaurus-preset-name

**Pull request merged**
