### PR TITLE
Add AirLyft in Astar Dapps

### PR DESCRIPTION
**Pull request by rmagon**
Adding information about the AirLyft dApp that is used by the Astar community for engagement and learning programs.

### CODE REVIEW

**Review by DrW3RK — COMMENTED** [review]
Thanks for adding this content to the Wiki. Although, this section is for apps developed on Astar blockchain and not for promotions on it. 

We might be able to list https://airlyft.one/communities?ecosystem=POLKADOT on the Wiki in an appropriate section. Let me get back to you.

**Comment by rmagon** [comment]
> Thanks for adding this content to the Wiki. Although, this section is for apps developed on Astar blockchain and not for promotions on it.
> 
> We might be able to list https://airlyft.one/communities?ecosystem=POLKADOT on the Wiki in an appropriate section. Let me get back to you.

Thank you so much for your quick response! We just wanted to add it to the wiki so that the campaigns are easier to discover, but fair enough . If you think we can add https://airlyft.one/communities?ecosystem=POLKADOT to the wiki please let me know the appropriate section & I will create the pull request for the same. Highly appreciate your support.

_Update: (PS: AirLyft also has contracts deployed on astar so even though it's 'used' for campaigns it also is in theory an app developed on astar as well - hence it's also in the [dapp staking system](https://portal.astar.network/astar/dapp-staking/dapp?dapp=0x22e1aa6bafb9965523cc33a5bfd2e4d3326a23e4) - but your suggestion is good too!)_

**Comment by DrW3RK** [comment]
Thanks for understanding. Please check the new PR on the Wiki. Happy to merge after you approve.

**Comment by rmagon** [comment]
> Thanks for understanding. Please check the new PR on the Wiki. Happy to merge after you approve.

Looks good, we can merge that one, thank you

**Pull request closed without merging**
